version: "3.8"

services:
  odtp:
    build: .
    image: odtp
    privileged: true
    ports:
      - ${ODTP_DASHBOARD_PORT}:${ODTP_DASHBOARD_PORT}
      - "8501:8501"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ODTP_PATH}:${ODTP_PATH}
    environment:
      ODTP_PATH: ${ODTP_PATH}
      ODTP_MONGO_SERVER: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@mongodb-instance:27017/
      ODTP_S3_SERVER: http://minio-instance:9000
      ODTP_BUCKET_NAME: ${ODTP_BUCKET_NAME}
      ODTP_ACCESS_KEY: ${ODTP_ACCESS_KEY}
      ODTP_SECRET_KEY: ${ODTP_SECRET_KEY}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      ODTP_MONGO_DB: ${ODTP_MONGO_DB}
      ODTP_DASHBOARD_PORT: ${ODTP_DASHBOARD_PORT}
      ODTP_DASHBOARD_JSON_EDITOR: ${ODTP_DASHBOARD_JSON_EDITOR}
      ODTP_LOG_LEVEL: ${ODTP_LOG_LEVEL}
      RUN_LOG_LEVEL: ${ODTP_LOG_LEVEL}

    stdin_open: true
    tty: true
    networks:
      - odtp-network
    depends_on:
      - mongodb-instance
      - mongodb-express
      - minio-instance


networks:
  odtp-network:
    driver: bridge
